trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.12'  # Adjust the Python version as needed

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install django djangorestframework markdown djangorestframework-simplejwt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python manage.py test
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testRunner: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    mergeTestResults: true

- script: |
    source venv/bin/activate
    python manage.py collectstatic --noinput
  workingDirectory: $(Build.SourcesDirectory)/Backend
  displayName: 'Collect static files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
